services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app

  linters:
    build:
      context: ./app/.linter
    volumes:
      - ./app/.linter/pyproject.toml:/opt/linters/pyproject.toml:ro
      - ./app/.linter/poetry.lock:/opt/linters/poetry.lock:ro
      - ./app:/app
    working_dir: /app
    profiles: [ "lint" ]

  editorconfig-checker:
    image: mstruebing/editorconfig-checker:v3.0.1
    volumes:
      - ./:/check
    profiles:
      - donotstart

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  app:
    driver: bridge
